import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {ReactLenis} from "../components/lib/lenis";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Darwis Shathibi | Student",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      ></meta>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
